### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by tinjaw** [Logitech/fw_updates#18]
I don't know the proper place to log this.

I want to modify the firmware for K780 so there is an option to keep the LED on for which device is currently connected, as I often lose track.

If need be, I can try coding it up. I assume your firmware is C. Is there a "plugin" architecture I can link into?

**Comment by ogay** [comment]
Hi Chaim,

Sorry, but there is no such plugin possibility at the moment.

Thanks,
Olivier
