### ISSUE TITLE
Can't update logitech unifying receiver via Linux fwupdmgr: cannot handle firmware requirement 'not-child' 

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [Logitech/fw_updates#20]
Please see [this bug report](https://github.com/hughsie/fwupd/issues/1139), filed under the `fwupdmgr`. Thanks.

**Comment by xnlcasad** [comment]
This is a problem with fwupd. Should be fixed when the [PR](https://github.com/hughsie/fwupd/pull/1144) gets accepted.
Closing as non-applicable.
