### ISSUE TITLE
Logitech Unifying Receiver for wireless mouse: scroll wheel problems

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [Logitech/fw_updates#21]
When the computer resumes from sleep, sometimes - I am unsure of the conditions - the mouse wheel either ceases to work entirely or yields only very slow scrolling. Removing and reinserting the dongle fixes the problem.

Possibly firmware version RQR24 solves the problem; I have only just updated ([with some trouble](https://github.com/hughsie/fwupd/issues/1139)) to that version.

It is possible that the software called `tlp` causes the problem. But the cause might also be a firmware bug. I suppose batteries might be at issue too, but I have no reason to think that the mouse's battery is low.

Linux Mint 19.1 x64 Cinnamon.
Linux kernel: 5.0.7-050007-generic

**Comment by xnlcasad** [comment]
This should not be a firmware problem. Your symptoms make me think of the high resolution scrolling support that was recently added to the kernel.
See:
https://patchwork.kernel.org/cover/10712839/
https://lkml.org/lkml/2018/11/22/625

@bentiss @whot

**Comment by bentiss** [comment]
This is definitively a bug in kernel v5.0. I am still unsure why, but it seems the kernel doesn't see the reconnect of the mouse, and thus doesn't send the correct high scroll setting, killing the mouse.

I am almost sure we are tracking this in a libinput issue but I can not seem to find out which.

Also, which mouse model are you using?

**Comment by LinuxOnTheDesktop** [comment]
Thanks. I have the M720 Triathlon.

There do appear to be several reports of this problem, including, for instance, [this one on the Arch Linux forum](https://bbs.archlinux.org/viewtopic.php?id=245501). I cannot manage to find the libinput bugtracker (though I have used it before); gitlab.gnome.org/ is not easy to navigate. I myself were prefer a fix in the kernel because that would be easier for me to obtain than a libinput fix.

**Comment by whot** [comment]
> I am almost sure we are tracking this in a libinput issue 

not yet, it was all off-list emails so far.

@LinuxOnTheDesktop, the libinput bug tracker is [on the fdo gitlab instance](https://gitlab.freedesktop.org/libinput/libinput/issues), not the gnome one. And yeah, this would have to be fixed in the kernel anyway, libinput doesn't even have code to handle the new axes yet, see [here](https://lists.freedesktop.org/archives/wayland-devel/2019-April/040377.html) for a summary.

**Comment by xnlcasad** [comment]
I would close this issue here as non-applicable. @bentiss is there a bug/issue somewhere to point this to ?

**Comment by owlstead** [comment]
As a workaround, I click the computer select button 3 times in quick succession. This seems to very reconnect the mouse without any noticeable latency, which solves the issue if it misbehaves after sleep. I've got kernel 5.4 of an Ubuntu LTS so I'm pretty annoyed that the problem persists, maybe the patch was not included in this kernel.
