### ISSUE TITLE
Possibly wrong filename ?

### ISSUE THREAD

**Issue by Dingo420** [Logitech/fw_updates#27]
https://github.com/Logitech/fw_updates/blob/master/RQR12/RQR12.09/RQR12.09_B0030.shex

i see that most of the firmware hex files are .hex (as expected), however the one listed above is .shex ? is this on purpose or by mistake?

**Comment by FFY00** [comment]
This is correct. `.shex` files are custom hex files the include a signature (so, signed hex files). The newer receives require a signature to be updated.

**Comment by Dingo420** [comment]
Good to know , sorry for my ignorance.
