### ISSUE TITLE
Flow on iPad OS

### ISSUE THREAD

**Issue by dominictinner** [Logitech/fw_updates#29]
I think it‘d be so nice to have to possibility to connect an iPad Pro to Logitech Flow. Now that iPad OS features full mouse and keyboard support it would make a lot of sense to me.

Here’s a reddit discussion about exactly this issue:
https://www.reddit.com/r/ipad/comments/bzylw1/logitech_flow/

Are you planning on including iPad OS into flow?

**Comment by xnlcasad** [comment]
@dominictinner This is probably not the best place to open issues regarding Logitech mice and keyboards software support. You'd be better off asking those questions [here.](https://support.logi.com/hc/en-us/community/topics/360001198873-Bluetooth-Wireless-and-Corded-Mice)

Even though I cannot answer your specific question, I can comment that currently Ipad OS would not allow a third party app to get cursor movement from the OS, thus there's no way to trigger screen switch when your cursor reaches the edge.

If you have other suggestions on how to get around that issue, please let me know.
