### ISSUE TITLE
Allow mapping of Break key for MX Keys

### ISSUE THREAD

**Issue by gregbrant2** [Logitech/fw_updates#32]
I'm a software developer and I use the Break key often, that is, before I got my MX Keys. Love the keyboard, but miss the Break key, and I can't map it in Logitech Options. Can you add Break as a mappable key so I can rebind one of the special keys above the numpad.

Thanks

**Comment by mviredaz** [comment]
Your request has been forwarded to the appropriate team.

Best regards.

**Comment by mygomel** [comment]
There is still no answer, I also encountered this problem and am disappointed, this keyboard is not for programmers.

**Comment by xnlcasad** [comment]
@mygomel It seems that using the key combination of "Ctrl+FN+B" either manually or mapping this combination on any F-key using Logitech Options may help. See: https://support.logi.com/hc/en-us/community/posts/360043998333-Pause-Break-key-on-MX-KEYS

That said, for future inquiries, may I suggest you to ask this kind of questions to [support.logitech.com](http://support.logitech.com/) ?

**Comment by RobDonovan** [comment]
Anyone know how to do this in 2023? That link doesn't work now :(

CTRL-FN-B is terrible to press, and I use it all the time as a coder.

I don't seem to be able to remap it to any Fx key as the software doesnt register the FN key press.

I can't believe they just got rid of keys that have been standard for years :(

**Comment by xnlcasad** [comment]
I hear your message, and as much as I'd like to help, this is not the right place to ask this question. This repository is about firmware updates for Logitech devices. It is possible to ask this question to Logitech support.
