### ISSUE TITLE
Will pressing keys during keyboard firmware update interrupt the progress?

### ISSUE THREAD

**Issue by gd08xxx** [Logitech/fw_updates#36]
Hi there, I am using MX keyboard. I tried updating the firmware and accidentally pressed control-c and control-d during the firmware update (i was trying to kill some terminal progress on my mac program). 

May I know whether pressing those keys will affect the firmware update of the keyboard? From what I know control-c and control-d kills progress for Unix commands and this can potentially kill some firmware update progress?

**Comment by hughsie** [comment]
If the keyboard is in bootloader mode then the keys won't register as keypresses, so it's perfectly safe.

**Comment by gd08xxx** [comment]
thanks a lot:) just to confirm, the keyboard is in bootloader mode when on a mac > logi options > firmware update > percentage progress indicator + red and green light blinking?

**Comment by hughsie** [comment]
> red and green light blinking

Exactly that.

**Comment by gd08xxx** [comment]
thanks!
