### ISSUE TITLE
Firmware update for Logitech K830

### ISSUE THREAD

**Issue by jvpeetz** [Logitech/fw_updates#9]
According to this [Logitech response](https://community.logitech.com/s/question/0D531000058b3B7CAI/logitech-response-to-research-findings) there is a firmware update for their keyboard K830 available regarding the _MouseJack_ vulnerability. Please, make this update also available for GNU/Linux users without access to the to date supported OS.

Regards,
jvp.

**Comment by xnlcasad** [comment]
The firmware update is already available on this [PR](https://github.com/Logitech/fw_updates/pull/8), it will be merged and made available thru [LVFS](https://fwupd.org/) in the coming days.

**Comment by jvpeetz** [comment]
Thank you for the information. The moment I filed this issue, I saw the pull request by mviredaz.
With the command `fwupdmgr get-devices` the K830 keyboards I would like to update show up as
```
  Flags:                updatable|registered
  DeviceVendor:         Logitech
  DeviceVendorId:       USB:0x046D
  Version:              RBK40.00_B0010
  VersionBootloader:    BOT21.00_B0005
```
while the unifying receivers have
```
  Flags:                updatable|supported|registered
```
Therefore, I thought the K830 keyboard is missing support.
